# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12' ]
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node }}
     - name: restore lerna
       uses: actions/cache@v2
       with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
     - name: Install dependencies
       run: |
        yarn

  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12' ]
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node }}
     - name: Load node_modules
       uses: actions/cache@v2
       with:
        path: |
            node_modules
            */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
     - run: yarn run lint
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: install
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v1
     - name: Load node_modules
       uses: actions/cache@v2
       with:
        path: |
            node_modules
            */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
     - run: yarn run build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Publish
        run: |
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            lerna publish --conventional-commits --cd-version=${{git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"}} --yes
          else
            echo "Not a release, skipping publish"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
     